---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)

```

```{r load_data}

tuesdata <- tidytuesdayR::tt_load('2021-03-09')
raw_bechdel <- tuesdata[["raw_bechdel"]]
movies <- tuesdata[["movies"]]

```


```{r clean_data}
reject = c("test", "imdb", "budget", "domgross", "intgross", "code", "period_code", "decade_code", "imdb_id", "response", "poster", "error")

clean_movies <- movies %>%
  select(!reject) %>%
  rename('budget' = budget_2013,
         'domgross' = domgross_2013,
         'intgross' = intgross_2013)

```


```{r pass_and_fail}

movies %>%
  group_by(binary) %>%
  select(binary) %>%
  count() %>%
  ggplot(aes(x = binary, y = n)) +
  geom_col()

```

```{r passes_fails_per_year}

clean_movies %>%
  group_by(year, binary) %>%
  select(year, binary) %>%
  count() %>%
  ggplot(aes(x=year, y=n, colour=binary)) +
  geom_line(size = 1) +
  labs(title = "Number of movies per year",
       subtitle = "By their Bechdel Test result",
       x = "Year",
       y = "Number of movies") +
  theme_minimal()  

```

